### ISSUE TITLE
The Lumage team sends their regards

### ISSUE THREAD

**Issue by y-ack** [MrNbaYoh/mrnbayoh.github.io#1]
Well see now sunflower I'm afraid you've made a bit of a mistake here~♫
"lumage" is neither a team nor the discoverer of this cute little insect.
No, you see, _sunflower_, this bug has been known to many people in the SmileBASIC community for much time.  The bouquet you seem to be referring to primarily did Western research on it.  Either way, a more accurate title would be "the smilebasic source community" I do believe~♪.

tc;dr I'm Lumage and I don't really want to be associated with this thank you very much.

**Comment by MrNbaYoh** [comment]
Well, it seems I made a mistake sorry for that.
